#!/usr/bin/env node
/**
 * tasks-sync.js
 *
 * Modes:
 *   node tasks-sync.js                        — rebuild .tasks/_index.md
 *   node tasks-sync.js --list                 — print all tasks to stdout
 *   node tasks-sync.js --list --status=dev-done — filter by status
 *   node tasks-sync.js --view TASK-INFRA-0001  — print one task file to stdout
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ─── paths ────────────────────────────────────────────────────────────────────
const ROOT = path.resolve(__dirname, '../..');
const TASKS_DIR = path.join(ROOT, '.tasks');
const INDEX_FILE = path.join(TASKS_DIR, '_index.md');

// ─── frontmatter parser ───────────────────────────────────────────────────────
function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const yaml = match[1];
  const result = {};
  for (const line of yaml.split('\n')) {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;
    const key = line.slice(0, colonIdx).trim();
    const raw = line.slice(colonIdx + 1).trim();
    // strip inline comments and quotes
    const value = raw.replace(/#.*$/, '').trim().replace(/^["']|["']$/g, '');
    if (value) result[key] = value;
  }
  return result;
}

// ─── collect all task files (recursive) ─────────────────────────────────────
function collectTasks() {
  const entries = [];

  function walk(dir) {
    for (const name of fs.readdirSync(dir).sort()) {
      if (name.startsWith('_')) continue; // skip _index.md, _templates/
      const full = path.join(dir, name);
      const stat = fs.statSync(full);
      if (stat.isDirectory()) {
        walk(full);
      } else if (/^TASK-.+\.md$/.test(name)) {
        entries.push({ file: name, filePath: full });
      }
    }
  }

  walk(TASKS_DIR);

  return entries.map(({ file, filePath }) => {
    const content = fs.readFileSync(filePath, 'utf-8');
    const meta = parseFrontmatter(content);
    const rel = path.relative(TASKS_DIR, filePath);
    const domain = rel.includes(path.sep) ? rel.split(path.sep)[0] : '—';
    return {
      file,
      filePath,
      domain,
      id: meta.id || file.replace('.md', ''),
      title: meta.title || '(no title)',
      status: meta.status || 'unknown',
      assignee: meta.assignee || '—',
      updated: meta.updated || '—',
      priority: meta.priority || '—',
    };
  });
}

// ─── find task file across subdirectories ────────────────────────────────────
function findTaskFile(taskId) {
  function walk(dir) {
    for (const name of fs.readdirSync(dir)) {
      if (name.startsWith('_')) continue;
      const full = path.join(dir, name);
      const stat = fs.statSync(full);
      if (stat.isDirectory()) {
        const found = walk(full);
        if (found) return found;
      } else if (name === `${taskId}.md`) {
        return full;
      }
    }
    return null;
  }
  return walk(TASKS_DIR);
}

// ─── status order for grouping ────────────────────────────────────────────────
const STATUS_ORDER = [
  'in-dev',
  'spec-ready',
  'spec-pending',
  'draft',
  'dev-done',
  'test-fail',
  'test-pass',
  'closed',
  'unknown',
];

function statusRank(s) {
  const idx = STATUS_ORDER.indexOf(s);
  return idx === -1 ? STATUS_ORDER.length : idx;
}

// ─── build index markdown ─────────────────────────────────────────────────────
function buildIndex(tasks) {
  const byStatus = {};
  for (const t of tasks) {
    if (!byStatus[t.status]) byStatus[t.status] = [];
    byStatus[t.status].push(t);
  }

  const statuses = Object.keys(byStatus).sort((a, b) => statusRank(a) - statusRank(b));

  const lines = [
    '# Task Index',
    '',
    '> Auto-generated by `pnpm run tasks:sync`. Do not edit manually.',
    `> Last updated: ${new Date().toISOString().slice(0, 10)}`,
    '',
  ];

  for (const status of statuses) {
    lines.push(`## ${status} (${byStatus[status].length})`);
    lines.push('');
    lines.push('| ID | Domain | Title | Assignee | Updated |');
    lines.push('|----|--------|-------|----------|---------|');
    for (const t of byStatus[status]) {
      const titleEsc = t.title.replace(/\|/g, '\\|');
      lines.push(`| ${t.id} | ${t.domain} | ${titleEsc} | ${t.assignee} | ${t.updated} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ─── CLI ──────────────────────────────────────────────────────────────────────
const args = process.argv.slice(2);
const isView = args.includes('--view');
const isList = args.includes('--list');
const statusFilter = (() => {
  const f = args.find(a => a.startsWith('--status='));
  return f ? f.split('=')[1] : null;
})();

if (isView) {
  // --view TASK-ID
  const taskId = args.find(a => !a.startsWith('-'));
  if (!taskId) {
    console.error('Usage: tasks-sync.js --view <TASK-ID>');
    process.exit(1);
  }
  const filePath = findTaskFile(taskId);
  if (!filePath) {
    console.error(`Task not found: ${taskId}`);
    process.exit(1);
  }
  process.stdout.write(fs.readFileSync(filePath, 'utf-8'));
  process.exit(0);
}

const tasks = collectTasks();

if (isList) {
  const filtered = statusFilter ? tasks.filter(t => t.status === statusFilter) : tasks;
  if (filtered.length === 0) {
    console.log(`No tasks found${statusFilter ? ` with status="${statusFilter}"` : ''}.`);
    process.exit(0);
  }
  console.log(`${'ID'.padEnd(24)} ${'STATUS'.padEnd(14)} ${'ASSIGNEE'.padEnd(12)} TITLE`);
  console.log('-'.repeat(80));
  for (const t of filtered) {
    console.log(`${t.id.padEnd(24)} ${t.status.padEnd(14)} ${t.assignee.padEnd(12)} ${t.title}`);
  }
  process.exit(0);
}

// default: rebuild _index.md
const md = buildIndex(tasks);
fs.writeFileSync(INDEX_FILE, md, 'utf-8');
console.log(`✓ .tasks/_index.md rebuilt (${tasks.length} tasks)`);
